### ISSUE TITLE
Help with compilation?

### ISSUE THREAD

**Issue by freakintoddles2** [ohnoitsalobo/midi-lights#1]
@ohnoitsalobo hello! I found your awesome midi-lights code and am trying to get it to compile in platform.io. I am a novice with these things and trying to get it to work, but platform.io doesn't seem to like the .ino files and wants everything to be .cpp files instead.  

I've been unsuccessful trying to convert this to .cpp and get it to compile - any help you're willing to give here would be much appreciated. I'm really excited to try this out! I have the hardware already working with a very simple sketch that blinks my LEDs when keyboard keys are pressed. Just need to get your amazing software running. Cheers.

**Comment by freakintoddles2** [comment]
Actually, I think I got it compliing and running, so I think all set. Cheers

**Comment by ohnoitsalobo** [comment]
Hey @freakintoddles2 sorry I missed this! Glad you were able to sort this out.
