### ISSUE TITLE
Unable to get hardware MIDI to be recognized

### ISSUE THREAD

**Issue by freakintoddles2** [ohnoitsalobo/midi-lights#2]
Hi @ohnoitsalobo - I got this compiled and running on my ESP8266 and the LEDS run great in 'automatic' mode. The trouble is I can't get it to respond to MIDI input via the RX pin (connected to my piano via midi coupler breakout board).

I have verified the hardware is hooked up correctly and working with a simpler sketch that just blinks all the LEDs each time a key is pressed, so I know that works fine.

When I use your code though, I can't get it to respond to any key presses.

I have updated everything that I can find to tell it that I'm using hardware midi and not apple/virtual midi. In MIDI.ino I have #define wired_MIDI 1   set and wireless set to 0. 

I would appreciate any guidance you can share to get this working. Thank you!

**Comment by freakintoddles2** [comment]
so, I found that if I set the mode to _midi at boot, it works. What's not working is the detection to pull it out of _auto mode once notes are being played 🤔

**Comment by ohnoitsalobo** [comment]
Hey @freakintoddles2 sorry I just saw this, I'll see if I can take a look. Were you able to fix it? The last time I tried it before uploading the code it was working, maybe library updates might have broken something.
